spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/mydb
#    username: myuser
#    password: mypassword
    url: jdbc:mysql:///DentistryManagementSystem?cloudSqlInstance=red-carver-425403-d9:us-central1:dentistrymanagement&socketFactory=com.google.cloud.sql.mysql.SocketFactory
    username: root
    password: Haha123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: dentistrysunflower@gmail.com
    password: hjmewqpnqgnobvcq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  cloud:
    gcp:
      sql:
        database-name: DentistryManagementSystem
        instance-connection-name: red-carver-425403-d9:us-central1:dentistrymanagement


secret_key:
  hs256: b1b61a49c7ad56cc29e71343a2fbbed93e0d459c3ac7949dd39f401236fd87d9

app:
  cors:
    allowed-origins: http://localhost:3000
