name: Jira Issue Update Workflow

on:
  push:
    branches:
      - master

jobs:
  check-commit-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check commit message
        id: check_message
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          echo "Commit message: $COMMIT_MESSAGE"
          if echo "$COMMIT_MESSAGE" | grep -Eq '^[A-Z]+[0-9]+ - .+$'; then
            ISSUE_KEY=$(echo $COMMIT_MESSAGE | grep -oE '^[A-Z]+[0-9]+')
            echo "::set-output name=issue_key::$ISSUE_KEY"
          else
            echo "Commit message does not match the required format."
            exit 1
          fi

  run-tests:
    runs-on: ubuntu-latest
    needs: check-commit-message
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Run tests
        id: run_tests
        run: |
          mvn test
        continue-on-error: true

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: target/surefire-reports

      - name: Set test result status
        id: test_status
        run: |
          if [ ${{ steps.run_tests.outcome }} == 'success' ]; then
            echo "::set-output name=status::success"
          else
            echo "::set-output name=status::failure"
          fi

  update-jira:
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
      - name: Install Jira client
        run: npm install -g jira-client

      - name: Update Jira issue
        env:
          JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        run: |
          ISSUE_KEY=${{ needs.check-commit-message.outputs.issue_key }}
          STATUS=${{ needs.run-tests.outputs.status }}
          if [ "$STATUS" == "success" ]; then
            jira-client transition -i $ISSUE_KEY -t Done
          else
            jira-client transition -i $ISSUE_KEY -t "In Progress"
            jira-client update-issue -i $ISSUE_KEY --type Bug
